instanceID: "17608074"

http:
  listener:
    host: "0.0.0.0"
    port: "8082"
  requester:
    sms:
      host: "api.authkey.io"
      port: ""
      path: "/request"

    
    


    
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    
                                                                                        
                                                                                            
                                                                                                
                                                                                                    
                                                                                                        
                                                                                                            
                                                                                                                
                                                                                                                    
                                                                                                                        
                                                                                                                            
                                                                                                                                
                                                                                                                                    
                                                                                                                                            
sfdc:
  username: "kumarmuletraining1@gmail.com"
  password: "ABCD@1234@abcd"
  securityToken: "whLO4wdVTLZnB1WGphxoZpl4"



