#%RAML 1.0
title: customer-xpapi-raml
description: This API is used by Frontend system to interect with customer related API.
version: 1.0.0

traits:
  common-header : !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/traits/header-common-trait.raml
  authorization-header : !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/traits/header-jwt-authorization-trait.raml

types:
  error-dataType : !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/dataTypes/error-dataType.raml
  post-registration-request : !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/dataTypes/post-registration-request-dataType.raml
  post-registration-response : !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/dataTypes/post-registration-response-dataType.raml

/customers:
  /registration:
    post:
      is:
        - common-header
        - authorization-header
      body:
        application/json:
          type: post-registration-request 
          example: !include /examples/post-registration-request-example.json
      responses:
        201:
          body:
            application/json:
              type: post-registration-response
              example: !include /examples/post-registration-response-example.json
                
        400:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/examples/error-400-response-example.json                      
        401:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/examples/error-401-response-example.json
        404:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/examples/error-404-response-example.json
        500:
          body:
            application/json:
              type: error-dataType  
              example: !include /exchange_modules/a8660bbd-d3c6-42e0-9530-f0ed6adc32ba/common-fragment/1.0.0/examples/error-500-response-example.json
                         
