instanceID: "17608132"
http:
  listener:
    host: "0.0.0.0"
    port: "8082"
  requester:
    customer:
      sapi:
        host: "0.0.0.0"
        port: "8081"
        pathCustomerState: "/api/customerState"
        pathVerification: "/api/verification"